sudo: false
language: node_js
services:
- docker
node_js:
- 7.4.0
env:
  matrix:
  - CXX=g++-4.8
  global:
  - DOCKER_IMAGE_NAME=kimwijk/react-portfolio
  - COMMIT=${TRAVIS_COMMIT::8}
  - secure: MQcZ1cC7oMObmgSTkqMTaM/oDSFZrHX1YJQuFZKPLCAqABTYJMWvw/regSxBZEzDpWePgCFePX2P5VURKJ9vDtKRiQe6RXROJqsnKBCzhbD6xaCk0UipGiPZvZtPVpODr2z23UQHt3+FjHNDd66Hq8sOHadCy9HGEIvPPKt7LeyNvCY+2Qj0u8+zU2CLtCyiuk0CY6Ioky0p1sDNOq0pxWXkhw7CCKmn7WYDMc1qlQ0jsv9qiBvDaMO+2XBjYb1d/hbgvSQlsXHz9nyUtOoZb/fDLoENp9H/dmTmhpnivFEPGvUNcsDwUN3Kafd0ywgHWw7JgDBk5NbeHpMvQW2weZnfE9XqRsntZCWr9BCRvQwSs/QONhM2P/pu01Xd4Wb2+j9EMtcxhvUYb9VRQPsYk7hVF6Lk8ds2oiVACGXllW8/LL/vnGbvF3RhAgcZ2sa2XP4qfjks+ABT6/96zxTGB/HAR9rZwfvwm6Ml4wQd+FkAkLBx7K6JDHsMvkzQepXRpfJYOjkvTCIWqLn4MC0/qc3Ywc2/VDns/GyCURycfNQMu6dcDC95a42FMrWgMk6a7qc5U7mYzqPTGoDB5nWjQKLIEu4CeNvH44VAxK4pYM127vwatfpdwETfaH4BVgTF6CgJNts0CCNmdhdHpVnp9+UsdMsPqs/CbG9ZkfTh0hk=
  - secure: t29gtZC2JsunCb8OCLZAbFkVUnc37MsUhxy/S9iJQX3SnJmzBTEPl+l34Y8bq7hbmdc3mWFPBlzKo2oenY8/jv/+JZ6sr1VW0PRvHcSrJTXP3Gg2lOp7tv94IMjSEIqYJK45lo48lXnFIhyzYCHGUlX1Egko0HG1JknN+AVKzyizWWF55XAqcmHn8ak85MhxDqh5i7yJhCiptLeQJXTWkybpc2Wnh75vORlw1kDqtxArp8i48icBFy95M2bJGA7UJZt16BvPu2jfNLIgGWU2F1bYXJZCRDkwvjkETJqYXZ12rQvzOrT178Z8/QZa2nom8N6yM5FgnUxFtGXZ6Vi1Ggod53ZHz0+oHurCUU9BdaT8w1WmbO5n2rEMWjKgTWUOoh8qsZP2DRzznv8zKgC5GQdpLWH6sNcDRp42mnDABvaXupabkoBgWLiBhFCZltDm2ZhoM0mM8rnjj6VoT0V5Z6wiDlRFvAiuE37MNhP2yACjBbs6qjx2FXOmZG5Y2Hag87dWgcqdlsdjg3biRwmfsE58jFbFQ5ubSU055HJd1+iwAcJ8uNjPQGSJusWrQK/6soevRhB54Y3f6yJ7Invy5FkTn7shy8fqH/ZnHhOICJYhNvm3FwZuekqXr2TgUYZQn58HbbDajOXvHiz6Y4VYt/VUDg3y6VEf4/Z/D/bkGlo=
  - secure: hGSkHvvHmKn2VsJ7f0o+rzCn4uxdNYzwx7Z2OXZTFmry1530g1Y0vXG8S4KQ5nSAsxBMk8pQuseOiUU6BG5VR3W7HOEcD+8zEcOa+v079b3Be1teBtmyAPo4HHVQICaDySSBbN2hajZGuZEmeRuOqLtTWjU79qz+LudGj0jzNS4giQOBvCkIdrRY/1P7k+Pn0/ouvPwVsrcLkTuPslN+CXlf+t3v+wwiwecp1ImkFnEnu5Q8z2BUYmZRbzG0Dx9Jowosv8bJferuVo4/iQUTa0enttKSTEZC6P5OkhUI3hM3uxKroyp0RTamKHNLdJYVFkrxo9zl6uGi1UilprPtMqkTMMY71guP5+y1OrxS1PFJWN3amfvBSD6IgDTA38hMHpMft1Clv7WAGVYgfUd2fmif4SaX+3Bwlt+THNivSYKC8sEd6lHeUSEHJcbwU579CxjIbWZXIcXzxNqsljycUsOU0pFmq+aGI0nvYIgQj/Ea4lJxvoE+PCka+K7usiDSk/kDzbf+srA00PEpAfMGDA5vK9L8PxRkSNbDRwbN2glC3wk+8K91l8DgmC7GwCUBNztSLJVwnBf9PjBNjFMBP3/30hW7ThLJc7xsaciR+7j0YEpltS3ePBIdACti9rCuj/flJCbvXcmcOH48IhGiXIYodmtrWZUnvJQmasQs4eU=
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
cache:
  directories:
  - node_modules
branches:
  only:
  - master
after_success:
- docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USER" -p="$DOCKER_PASS"
- docker build -f Dockerfile -t $DOCKER_IMAGE_NAME .
- if [ ! -z "$TRAVIS_TAG" ]; then docker tag $DOCKER_IMAGE_NAME:latest $DOCKER_IMAGE_NAME:$TRAVIS_TAG;
  fi
- if [ "$TRAVIS_BRANCH" == "master" ]; then docker push $DOCKER_IMAGE_NAME; fi
