sudo: false
language: node_js
services:
- docker
node_js:
- 7.4.0
env:
  matrix:
  - CXX=g++-4.8
  global:
  - DOCKER_IMAGE_NAME=kimwijk/react-portfolio
  - COMMIT=${TRAVIS_COMMIT::8}
  - secure: X7kx3vSgFzHG9FVkw2QfwD8SCrr3WOjCvbXNe8BQWLgfwksmTicTh3pMdvD5RcZgYa1tf5CyP1H21eGJx2k3K7ybOngEDgQaYFKv3ZjWKjSA3WNIG/cArRLcNl2Zygs1hYdslWWCR6UwVeHOvr7ercuKLUgSFgoLDNUC57iCy37SuwJOpcvSMw1aWXYgZNSsgWMQsUPSde7RoaUdJBiuhIELhESqu+07n7p4xbr8GfwyNl+z8YwnBdvcwLX19AaCuYS0179RDfyFeGGWha4ryxAiB0tUy1FFpPf6gPpZ/ZE+DO9xZH4dL/Bjkp/Il3k7Ury+crW7e7Xuy0FkwOOMmo/gNqEtUjV3z/cS8HtyvJHXNacDng0dPBPCUDdbN/MzP1HEOLjXYnau4eCC4Bfr2vY31qfMIII8AO1kfvniTgpAm1PCcecFCUckrJcvQCyGltxVdLV//hzFhSk3pR/5Bhg0JPVvhSooTjl+QszpcDyEup9KoR7+IK3GqBCeTOrf4JUL0ebOVB8I0leL1Dcfthk0KDozJWDy2DKe6uL+a97VqE/2jRfdEUi/mMVPS3y22NpFIFsi03FSwEg2YNlR/+6OhfhfO7DR2UcoeIH7Li3JGS/FIMKAiAU8GIyAgJi2Vuf+Exl9AwJMAW+Ao3kfeci7Hsaho+GOGMPgvNons1Y=
  - secure: ZAkTkwaQtIEpjnE0YilMPlnUwAwixcgU3kgw9ZDEAgNShCH2+7hEo3b1TNUm1XTB7OX9G4WBY90yS7m+rpvo/ho95BEDWEXOyP5u8UGTJQfWbMwHl6S0y9+B5bMFZfCDY9JC7EEv7ec/MlAH0r9f5miFGbn0AUCIvZtuGhU8W6AoRIZ0OCznrONFY0PMwOSsrQU/u2dOp+bsCe3EthdiZQUIzMWdRziYJwKseyY6YX3w6f+vfmsIf7JzxcBN7jnfgXuGAnc0jMZ7T4T4HOULnkrIcQZfRdxT2JZWhN40vs92/vFx97X4IcycoC5ux8oa+wGMcc2eqcEhxRN+OLA8bN908YvZExOIAaWrpFMqgCYWXo1G3eK+yQjKXveiEUo4APC5OKCQRTl06VZ6kMD9P2EXLn8mYVrH9rUE14Je7kUQLy+F06DmvnWt/uurTeTRt1isQ6AiaedA/Mhr9/iXNVwMoUVaAlnhrgI/ZWYfQ4TU9XbB8vH5T7tVyl/8aeMvMs9TV4UOb05FxJap6LAj1/X7dZ8nnQr/RpZ+pEyk8W1mDT2R1kmfj7JJsSAKoqOexqlMadBZ5i5JsZVqZbrP9s8EtUkoo8QYPqDYX1aMiwUK75qQkGggfg0h14Zcxq8EKcp6Xiobymhyjdvdz6FJvVtg4tqOV5e4BKB3QjikzgQ=
  - secure: akmYi/j07QtyuQ4/2ONbzI5HYGhccPf2D2Cvs5Ll4pKduJ0idUTDrvWB49D9cLqkan1KzcBxBQ2wa0BOVwHixioxkj3TIzEVt448erbgjI466pB5bduztMNU9+6LcGfGcY/1spEVqyJKtJQSkbuMfoUYbdcsF/hUc4NLGQAsiM/Y0SOhELSewEbtjr7B0ivhcEJ+RHFGBI1eXtkjU/DHryA1SzyHiCYE0rdRTOFc5k77NrYu152FSbyOxKea8kJBdne3N91UXIYv2HZWD5AwS3GHAkqWyFdYYKzqPFzwBSM99L+2yM11Bj58keb+pIH5jpktNT5ALr5VRxUV6XWE5rLyTQvKrRqRi9n6zMTHjkdkVAwKe6SLDNLhtQz3ZIQSy1eDkr019IA/Vd7VEDraKllkcFc3cYKL32KYfP6nqsGrMBmbEsBdiFfcfmRIgEFvRSzZpUte51paqF+rcddI96XO8Fh4xwyzGlvj/xQpg3RYv5yltuTIYESMtbHIFm+Piuudg9GIwbQHd9NCCtZDcdDbW0rMIda8Vy7nkrcZDBy45LtgBz6fEfy78TGnXq9v7M7e5X8jGJL2JyMJiQLK8swWkip2LXPiYdd5sQKzfVCTG6xWUqlp6pUw01z2d1Zig2DhxLBegn3os2ytc98qb2GFbk7+7y3qsHB5o+2mwnI=
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
cache:
  directories:
  - node_modules
branches:
  only:
  - master
after_success:
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USER" -p="$DOCKER_PASS"
  - docker build -f Dockerfile -t $DOCKER_IMAGE_NAME .
  - if [ ! -z "$TRAVIS_TAG" ]; then
        docker tag $DOCKER_IMAGE_NAME:latest $DOCKER_IMAGE_NAME:$TRAVIS_TAG;
      fi
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
        docker push $DOCKER_IMAGE_NAME;
      fi
