sudo: false
language: node_js
services:
- docker
node_js:
- 8.9.4
env:
  matrix:
  - CXX=g++-4.8
  global:
  - DOCKER_IMAGE_NAME=kimwijk/react-portfolio
  - COMMIT=${TRAVIS_COMMIT::8}
  - secure: n8LlpYGT5qH1CMzY5FGwApxoMRagoxYABkzZrShqVaSRN/1yS48ONuN79Ykn0pCce5mskOyJBKWqvcvwJWLx2fVTLOlHJMZ5/vGQAk0CU418k6NpQ+a6UJzFH9spLE9mtHtMKhltVBiyqcG2HauGjunZDZo/R7f22ShXYLl7zFiFNBmNJyJgVFK7r8BgUm+DLnE4pkcHV01ms82jeWeLjMUVl1WET65iprd/Y1AzB+0GE3qAJp5eezBmhSPSGAqncJSOur7+L09UdkKGqnmUxA0OFM7iwUhTKjnuFCi+Bg/t2I4SisKbz/FDnHfjSGnEHyWF/Q60VRv1qumKgZEqVxReX+2CMs+HKWNxCa2puJ3IbCBWkMScWJYT6Su4QNBMPbp15UDxbMxJCkd/H7OekN7HYWrbc9WZMh4VtORoKdoEDIhxSbI3UkiGGKS0FBCLLU3qotbFFn+peVRk+xz8RzlDP6cwv4FP7J3vq1koH7ND5uhEihDaddY4Y7//1E2/+yMIPiUw9cq2FJOONOQe1WVs2Ns6pzh53lAIRG8uy9MsWn3vgZFonDylL1fgbJG1li6c66UXQIV7B89w6gpjRnK/wIsShiAEgJ7bCJcTgP4Phcemf5lE4wH2tRMrWsPCB0kEJNyhGYqPdpfZMtUF+3daxFS5ohYfTiZJhUv3yuE=
  - secure: BBG2zo+ar74p/AcbgNr430cVRevIHsWoGLGwcfDidJRVPEXBum5yh0Vn8ogmJriSk/KVStTD5evHuVi164/dAq85ZCmYeBN62JvymR4eDDg8m9z57P6b/wz4GNhJYNPp0N5NZh2KCHOz3w4eFOMfnfGnkHtzVGsgYvXAwx5KZRjDHHbaA6KJ3/W6yRFujz/ZigKa2uZFNmlYgMiBW8v6u5GujJEFs4ccrdxcrh3jI4mV/pMTzvURuUjrstCbQB9pJmfk9Ds0Sy9CK/m1C2ftbUqhGubO/PwCyzIX3CLEJ8HTrlOoFaAPPohs6JZK8m77Lrd4EcVHJiQd1blszWDjQcDhOeVjH7YTCrErvfA5yeozojcpS53NBjh34V7PeF564cqG1lEnx4bFsCfxvZSA3AKSGYNaFcEdG6NBHH5yQTRfjxqenzUbx1HL5EbcXaHDqAK3C35zYrnKTcKp7zPauXf/2QC8DdE7cRbFwnFZLbkzFw+v4yIRLticnTp/dsHasvdb9rS8GmhKm72IXx1RIWVt1b9yWOqug2sqtuj81JoLJCnVHwV8JM13GcFur+koao757pmIPXMql72HEeSeQndq+XHcoBAnUCAq72GT8uxKZO1VtFpsdh2CrDdKgWUXEMA5/HylzuatpDP7RINRiqwn1SqSF3GVJC5fr3x+NHc=
  - secure: WtvQL/oO0gIqFriZEZ/5boF97SH7SPqVsTm/DfrUE1oKH24c+txcqy02jKRdg5sz0kUVAwAJ2ZZnAUSXCpivyzYZIRk/wbWa1BOPVAzwNICCk4f+WP9rM9iOlN89ooMp1078wJMmrkNiNoSvJvfyY+9CcRRHddHV35YCgVblWF8/ajAf1Pkv/MY21uZlmg/kOT5/V0Xk2vE0aW8tFfDhHCEjozp0lI95A+C0RjuSQpVm0M1OVOajUj9DTzDFWrs7NoBfRT0Ubw8MN4KR+Q2/QBbLqFYIaNgWD/N5pL+/oUM610wcq+n8ctydyqMKtiL4ZbvTMb3VStNmggads3vz8NwWFQZACDliLXsjIuWMXUK4bkysPWQovfnAQX7FJSzYCLVSYfwfLKyN1Bevbc30gr48i2OpmfABPOKZ1sluJCUU9eOwwUq+z7worUgFBFByS67K7PF3MPRNrGYcUNcf1qwviSWCRzd21hKDjRDiqCBRroFI7zU0cNMYaNKwrYPt9YhSEZzB7WKfWAXjimCOLtsWZUudAYEiKc/QZIfhRsH1nufN9yZst81Tgsd1qOdo3gCx7VKgVkNJ2l4ffr80p3dchAWw1aErEs1sigNs0BelfTLe2rwHTuhPaeL/HcSc2cub0tn25z21Rl5GoR+h9i1vHDZBXd3toYPKOZmutvA=
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
cache:
  directories:
  - node_modules
branches:
  only:
  - master
after_success:
- docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USER" -p="$DOCKER_PASS"
- docker build -f Dockerfile -t $DOCKER_IMAGE_NAME .
- if [ ! -z "$TRAVIS_TAG" ]; then docker tag $DOCKER_IMAGE_NAME:latest $DOCKER_USER/$DOCKER_IMAGE_NAME:$TRAVIS_TAG;
  fi
- if [ "$TRAVIS_BRANCH" == "master" ]; then docker push $DOCKER_USER/$DOCKER_IMAGE_NAME; fi
