const fakeDB = [
  {
    id: 'abcd190d',
    title: 'Welcome!',
    slug: 'the-journey-of-building-welcome-app',
    subtitle: 'We are a Movement Dedicated to Connect Newcomers with Welcomers',
    tags: ['Startup', 'Development', 'Innovation', 'Impact Tech', 'Founder'],
    picture: '/media/15440459_1159469577493205_5072693347909689122_o.jpg',
    description: 'I volunteered to lead the technical process of developing a hybrid app where newcomers in Sweden can connect with locals.\n\n We engaged a team of about 20 contributors/volunteers that collaborated together to launch the very first version of Welcome App in the winter 2015.\n\n My contribution included sprint planning, technical architecture, programming, best practices and recruitment of developers.\n\n Today Welcome App is funded and has a team working full-time at Norrsken House to scale it further.',
  },
  {
    id: 'xys19asdasd0a',
    tags: ['Tech Lead', 'Front end', 'Lean Startup'],
    title: 'OOAK',
    slug: 'ooak-a-personalised-vintage-app',
    subtitle: 'A Personalised Vintage App',
    picture: '/media/ooak-a-personalised-vintage-app.jpg',
    description: 'Lead the technical process together with a team of great developers.\n\n My days included planning, experimentation with lean methodologies and balancing user-driven development with scalable components.\n\n Our team covered every step from concept to launch and scale up within the Schibsted Media Group. Worked closely, on an everyday basis, with Product Managers, UX/UI designers and our end users which made us fast and unstoppable.',
  },
  {
    id: 'xys19asdsds3asd0a',
    tags: ['Founder', 'Lean Startup', 'Design', 'Front end'],
    title: 'Dine',
    slug: 'dine-app',
    subtitle: 'Dine is social dining for food-lovers by food-lovers. ',
    picture: '/media/dine-hero.jpg',
    description: 'With Dine you can easily find a home-chef in your area to go for a home cooked meal and pay less than you do at a regular restaurant.\n\n If you enjoy cooking, invite a stranger over for a meal and earn some extra money.',
  },
  {
    id: 'xys190a',
    tags: ['Product Development', 'Front End', 'Back end', 'Architecture', 'Microservices'],
    title: 'Marketing Room',
    slug: 'marketing-room-collect-leads-and-compaigns',
    subtitle: 'Manage all campaigns and leads from one platform',
    picture: '/media/marketing-room-response.jpg',
    description: '',
  },
  {
    id: 'xys190b',
    tags: ['Design'],
    title: 'The Recipe',
    slug: 'cloth-talk-part-ii',
    subtitle: 'A recipe wallpaper of the human body',
    picture: '/media/ingredients.jpg',
    description: '',
  },
  {
    id: '128ssad043hd',
    tags: ['Front end', 'Back end', 'Game Development', 'Facebook'],
    title: 'Whac a robot!',
    slug: 'proteinfabrikken-whac-a-robot',
    subtitle: 'Interactive HTML5 Game',
    picture: '/media/whac-a-robot.jpg',
    client: 'Proteinfabrikken',
    description: '',
  },
  {
    id: '128sd043hf',
    tags: ['Design', 'Front end', 'Back end', 'UX'],
    title: 'Fore!',
    slug: 'target-26',
    subtitle: 'Register your handicap and win a golf trip',
    picture: '/media/target-26.jpg',
    client: 'Norges Golfforbund',
    description: '',
  },
  {
    id: '128s32d0ad043hd',
    tags: ['Front end', 'Back end', 'Illustrations'],
    title: 'Pakk sekken!',
    slug: 'pakk-birkensekken',
    subtitle: 'Pack the bag and get ready for a norwegian "tur"',
    picture: '/media/pakk-birkensekken.jpg',
    client: 'Birken',
    description: '',
  },
  {
    id: '128s3as32fd0ad043hd',
    tags: ['Front end', 'Back end', 'Design'],
    title: 'LOOP',
    slug: 'loop-project-managment',
    subtitle: 'Inhouse project management system for sales and projects',
    picture: '/media/loop-project-management.jpg',
    client: '',
    description: '',
  },
  {
    id: '128s3as32fd052ad043hd',
    tags: ['Front end', 'Back end', 'Design', 'Illustrations'],
    title: 'Invite for a golf round',
    slug: 'kragero-golf-round',
    subtitle: 'A Facebook campaign to create engagement for Kragerö Resort',
    picture: '/media/kragero-resort-golf.jpg',
    client: 'Kragerö Resort',
    description: '',
  },
  {
    id: '128s3as32fd05as2ad043hd',
    tags: ['Design'],
    title: 'Webshop',
    slug: 'smartlager-webshop',
    subtitle: 'A complete remake of webshop',
    picture: '/media/smartlager-webshop.jpg',
    client: 'Smartlager',
    description: '',
  },
  {
    id: '128s3as32fd05aas32agd043hd',
    tags: ['Front end', 'Back end', 'Architecture', 'Design', 'UX'],
    title: 'Solid Response',
    slug: 'solid-response',
    subtitle: 'Manage your brands campaigns, follow the evolution and measure your ROI.',
    picture: '/media/solid-response.jpg',
    client: 'Inhouse',
    description: '',
  },
  {
    id: '128s3as132fd05asaas32agd043hd',
    tags: ['Front end', 'Back end'],
    title: 'Sushi time!',
    slug: 'raa-sushi-game',
    subtitle: 'Viral campaign to invite your friends for a sushi dinner',
    picture: '/media/ra-sushi.jpg',
    client: 'Rå Sudio',
    description: '',
  },
  {
    id: '128s3as132fd05asa31as32agd043hd',
    tags: ['Front end', 'Back end'],
    title: 'Invite to dinner',
    slug: 'castello-fyll-ett-bord',
    subtitle: 'Viral campaign to invite your friends for a dinner.',
    picture: '/media/castello-fyll-ett-bord.jpg',
    client: 'Arla',
    description: '',
  },
  {
    id: '128s3alxla132fd05asa31as32agd043hd',
    tags: ['Front end', 'Back end'],
    title: 'Activity timeline',
    slug: 'marketing-room-timeline',
    subtitle: 'See recent activity on your brand and respond to your customers instantly',
    picture: '/media/marketing-room-timeline.jpg',
    client: 'Inhouse',
    description: '',
  },
  {
    id: 'xys190s',
    tags: ['Front end', 'Back end', 'Game Development', 'UX'],
    title: 'Shop til u drop!',
    slug: 'proteinfabrikken-shop-til-u-drop',
    subtitle: 'An interactive game',
    picture: '/media/pf-shop-til-u-drop.jpg',
    client: 'Proteinfabrikken',
    description: '',
  },
  {
    id: '128sd04d',
    tags: ['Design', 'Front end', 'Back end', 'UX'],
    title: 'Save for something.',
    slug: 'sparebank1-savings-calculator',
    subtitle: 'Savings calculator developed for Sparebank1 in Norway',
    picture: '/media/sparebank1-sparkalkulator.jpg',
    client: 'Sparebank1',
    description: '',
  },
];

export default fakeDB;
